CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_INSTANCE_SEQ MAXVALUE 9223372036854775807 NO CYCLE;

SELECT setval(
    'BATCH_JOB_INSTANCE_SEQ',
    COALESCE((SELECT MAX(JOB_INSTANCE_ID) FROM BATCH_JOB_INSTANCE), 0) + 1,
    false
);
